# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use("seaborn-v0_8")
sns.set(font_scale=1.0)

df = pd.read_csv("/content/menstrual_absenteeism_50_countries.csv")

df.head()
df.info()
df.describe(include="all")

df.duplicated().sum(), df["Country"].duplicated().sum()

# Ensure numeric columns are numeric
num_cols = [
    "Girls_MHM_Education_Program_Coverage_%",
    "Schools_with_gender_separate_lockable_toilets_%",
    "Schools_with_bins_for_menstrual_waste_%",
    "Schools_providing_menstrual_products_%",
    "Girls_missing_school_during_menses_%",
    "Average_days_missed_per_cycle",
    "Reported_period_product_unaffordability_%",
    "Girls_aware_before_menarche_%",
    "Female_lower_secondary_completion_%",
    "Female_labor_force_participation_%",
    "Estimated_future_earnings_loss_%"
]

df[num_cols] = df[num_cols].apply(pd.to_numeric, errors="coerce")

# Missing values
df.isna().sum()

df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.tight_layout()
    plt.show()

grouped_income = df.groupby("Income_Group")[num_cols].agg(["mean", "std", "min", "max"])
grouped_income

grouped_region = df.groupby("Region")[num_cols].mean().round(1)
grouped_region

key_x = [
    "Schools_with_gender_separate_lockable_toilets_%",
    "Schools_with_bins_for_menstrual_waste_%",
    "Schools_providing_menstrual_products_%",
    "Girls_MHM_Education_Program_Coverage_%"
]

y = "Girls_missing_school_during_menses_%"

for col in key_x:
    plt.figure(figsize=(6,4))
    sns.scatterplot(data=df, x=col, y=y, hue="Income_Group")
    sns.regplot(data=df, x=col, y=y, scatter=False, ci=None, color="black")
    plt.title(f"{y} vs {col}")
    plt.tight_layout()
    plt.show()

targets = [
    "Female_lower_secondary_completion_%",
    "Female_labor_force_participation_%",
    "Estimated_future_earnings_loss_%"
]

for t in targets:
    plt.figure(figsize=(6,4))
    sns.scatterplot(data=df, x="Girls_missing_school_during_menses_%", y=t, hue="Income_Group")
    sns.regplot(data=df, x="Girls_missing_school_during_menses_%", y=t, scatter=False, ci=None, color="black")
    plt.title(f"{t} vs Girls_missing_school_during_menses_%")
    plt.tight_layout()
    plt.show()

for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(data=df, x="Income_Group", y=col)
    plt.title(f"{col} by Income Group")
    plt.tight_layout()
    plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(data=df, x="Region", y="Girls_missing_school_during_menses_%")
plt.xticks(rotation=45, ha="right")
plt.title("Girls_missing_school_during_menses_% by Region")
plt.tight_layout()
plt.show()

corr = df[num_cols].corr()

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", square=True)
plt.title("Correlation matrix of key variables")
plt.tight_layout()
plt.show()

corr_abs = corr["Girls_missing_school_during_menses_%"].sort_values(ascending=False)
corr_abs

df["School_MHM_Readiness_Index"] = (
    df["Schools_with_gender_separate_lockable_toilets_%"] +
    df["Schools_with_bins_for_menstrual_waste_%"] +
    df["Schools_providing_menstrual_products_%"]
) / 3

plt.figure(figsize=(6,4))
sns.scatterplot(data=df, x="School_MHM_Readiness_Index", y="Girls_missing_school_during_menses_%", hue="Income_Group")
sns.regplot(data=df, x="School_MHM_Readiness_Index", y="Girls_missing_school_during_menses_%", scatter=False, ci=None, color="black")
plt.title("Absenteeism vs School MHM Readiness Index")
plt.tight_layout()
plt.show()

import statsmodels.api as sm

X = df[[
    "School_MHM_Readiness_Index",
    "Girls_MHM_Education_Program_Coverage_%",
    "Reported_period_product_unaffordability_%",
]]
X = sm.add_constant(X)
y = df["Girls_missing_school_during_menses_%"]

model = sm.OLS(y, X).fit()
print(model.summary())